# Site settings
title: Cascadia Urban Analytics Cooperative
email: urbandat@uw.edu
description: > # this means to ignore newlines until "baseurl:"
  The work of a curious design student exploring landscape, data and cities
#baseurl: "/cuac/"  the subpath of your site, e.g. /blog/
url: "http://jesshami.github.io/cuac/" # the base hostname & protocol for your site
twitter_username: urbanuw
github_username:  cascadiadata

# Build settings
markdown: kramdown
#port: 4001
#paginate: 4
#paginate_path: "blog/page:num"