# Site settings
title: Cascadia Urban Analytics Cooperative
email: urbanuw@uw.edu
description: > # this means to ignore newlines until "baseurl:"
  The work of a curious design student exploring landscape, data and cities
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jesshami  
github_username:  jesshami

# Build settings
markdown: kramdown
port: 4001
#paginate: 4
#paginate_path: "blog/page:num"